# Site settings
title: Tian Zhi Wang
email: wtianzhi@gmail.com
description: "Freelance Web Developer"


# Build settings
markdown: kramdown
permalink: pretty

port: 9000

sass:
  sass_dir: assets/css
  style: :compressed
